language: php

sudo: false

#cache:
#  directories:
#    - "$HOME/.composer/cache/files"

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION="^3.4"
    - php: 7.1
      env: SYMFONY_VERSION="^4.0"
    - php: 7.1
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"
    - php: 7.2
      env: SYMFONY_VERSION="^3.4"
    - php: 7.2
      env: SYMFONY_VERSION="^4.0"
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"
  allow_failures:
    - php: 7.1
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"
    - php: nightly

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install:
    - composer update $COMPOSER_FLAGS --prefer-dist
    - cat composer.lock

script: vendor/bin/phpunit
