language: php

sudo: false

#cache:
#  directories:
#    - "$HOME/.composer/cache/files"

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

php:
  - 7.3
  - 7.4
  - nightly

matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION="^4.0"
    - php: 7.4
      env: SYMFONY_VERSION="^4.0"
  allow_failures:

    - php: nightly

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install:
    - composer update $COMPOSER_FLAGS --prefer-dist
    - cat composer.lock

script: vendor/bin/phpunit
