services:
    hostnet_entity_translation.enum.loader:
        class : Hostnet\Bundle\EntityTranslationBundle\Loader\EnumLoader
        arguments:
            - "@translation.loader.yml"
        tags:
            - { name: translation.loader, alias: enum }
